site_name: FastAPI Template
repo_name: cookiecutter-fastapi
repo_url: #
site_url: #
copyright: Fernando Celmer

nav:
    - Home: index.md
    - Getting Started: nav/getting-started.md
    - Development:
      - nav/development-guide.md
      - nav/release-notes.md

theme:
  name: simple-blog
  favicon: assets/fastapi.png
  logo: assets/fastapi.png
  theme_style: dark
  site_name_style: normal
  title_style: bold
